### ISSUE TITLE
Normalize headers/fields usage per spec

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/tableschema-js#57]
This library refers to headers including in docs. However in JTS itself we talk about fields.

Would it reduce confusion to change headers to fields throughout (both in docs and code)?

**Comment by rufuspollock** [comment]
In fact I'm a bit more confused now i realise that `Schema` has **both** `fields` property and `headers` property. Is `headers` just `field.name for field in fields`? If so maybe `fieldNames` would be better ...

**Comment by roll** [comment]
> Is headers just field.name for field in fields?
Yes

We has some discussion on this topic but we've decided to have both (`fields[x].name` and `headers`) for now. 

For example in `goodtables` terminology headers ans field names mean different things:
- `headers` is actual column names in data files
- `fieldNames` is Table Schema field names
For valid table it should be the same (match each other).

So here user could be interested exactly in headers term when exploring a table:
```
table.schema.headers
```
And because table is table-schema-valid this headers will match field names.

**Comment by rufuspollock** [comment]
@roll ok, that is useful clarification.

I do think this may be super confusing 😉  - especially if `headers` can differ from `fields.map(field => field.name)`

If it is useful to have `headers` (as defined) i'd consider being super explicit about what it is and signify this by renaming e.g.

```
headers => rawFieldNames
```

I know this is a bit more ugly but I've already run into this confusion myself and one other person.

**Comment by roll** [comment]
@rufuspollock 
In general I agree. After spec-v1 release I'll be doing review of stack API (and also work iteration on all libs). I suppose we could have `table.headers` and `schema.fieldNames` - it could be pretty natural.

**Comment by rufuspollock** [comment]
@roll i would avoid `table.headers` in general if you have the field names because it is super confusing - you need something more descriptive for what the headers actually are e.g. `rawHeaders`.

I'm not sure you need schema.fieldNames - you can get that from fields yourself pretty quickly.

**Comment by pwalsh** [comment]
@roll great thing to do, but not related to updating specs to v1. Please do not do until after updates related to specific v1 changes.
